name: Guildclash
main: Guildclash.Guildplugin
version: 1.0.0
commands: 
    guild:
        description: /guild help seite
        aliases: [g]
    yggdrasil:
        dresciption: Teleportiert dich zum Spawn des Yggdrasil
        aliases: [y]
    paste:
