name: Guildclash
main: Guildclash.Guildplugin
version: 1.0.0
commands: 
    guild:
        description: /guild help seite
        aliases: [g]
    gchat:
        description: Writes a message to your guild members